import type { Post } from "../data";

const deepLinkAnotherWayToOpenYourApp: Post = {
  slug: "deep-link-another-way-to-open-your-app",
  title: "Deep Link — Another Way to Open Your App",
  tag: "Android",
  date: "Dec 2022",
  readTime: "4 min read",
  excerpt: "One of the Android’s feature that we often see is when we click on the link (maybe on browser, chat, or another app) that refer to app, we will immediately directed to that app(If user already install it yet) or show the disambiguation dialog(if user don’t install it). This feature called Deep Link.",
  cover: "/assets/blog/deep-link-another-way-to-open-your-app/img-1.jpeg",
  link: "https://medium.com/@mrizqi070502/deep-link-another-way-to-open-your-app-7c3859404d1f",
  body: [
    { type: "paragraph", text: "One of the Android’s feature that we often see is when we click on the link (maybe on browser, chat, or another app) that refer to app, we will immediately directed to that app(If user already install it yet) or show the disambiguation dialog(if user don’t install it). This feature called Deep Link." },
    { type: "heading", text: "Different Types of Links" },
    { type: "paragraph", text: "In Android App, there 3 types of links that you can set." },
    { type: "heading", text: "1. Deep Links" },
    { type: "paragraph", text: "Deep links are URIs of any scheme. Scheme like https in website url(https://websitedomain). If user click on this link, a disambiguation dialog might appear (The dialog with some application option that can handle)." },
    { type: "image", src: "/assets/blog/deep-link-another-way-to-open-your-app/img-1.jpeg" },
    { type: "paragraph", text: "Disambiguation Dialog" },
    { type: "heading", text: "2. Web Links" },
    { type: "paragraph", text: "Web links are the more specific deep links. They only use HTTP and HTTPS scheme. On Android 12 or higher, clicking on the link will only shows content on the browser. On previous version, it will show disambiguation dialog." },
    { type: "heading", text: "3. Android App Links" },
    { type: "paragraph", text: "They like web links, only use HTTP and HTTPS scheme but contain **autoVerify** attribute. Android App Links only supported on Android 6 and up(API level 23). You can make your app opened directly from the link(of course with more step). Using this type, you can get some benefits like secure and specific, seamless user experience, android instant apps support, and engage users from google search." },
    { type: "heading", text: "Define Intent Filter" },
    { type: "paragraph", text: "In AndroidManifest.xml, you should add **<intent-filter>** tag to the activity you want to open for a link. Inside that, you should add another tags, those are" },
    { type: "paragraph", text: "1. **<action>** and specify the **android:name** attribute to **android.intent.action.VIEW**. This configuration makes the intent filter can be reached from **Google Search**. 2. **<data>**. Using this tag, you can specify the URI format for the intent filter. At minimum, you must include **android:scheme** attribute likes http, https, or custom scheme. You can also specify the host using **android:host** likes www.yourwebsite.com. Another useful attribute is **android:path** that allows you to specify path of the link. 3. **<category>**. You must add **BROWSABLE** and **DEFAULT** in **android:name** attribute at different tag. BROWSABLE makes the intent filter accessible from web browser. DEFAULT makes the app can respond to implicit intent." },
    { type: "paragraph", text: "Example of Intent Filter" },
    { type: "code", code: "<activity\n    android:name=\"com.example.deeplinkapp\"\n    >\n    <intent-filter>\n        <action android:name=\"android.intent.action.VIEW\" />\n        <category android:name=\"android.intent.category.DEFAULT\" />\n        <category android:name=\"android.intent.category.BROWSABLE\" />\n        <data android:scheme=\"http\"\n              android:host=\"www.example.com\"\n              android:path=\"/deeplink\" />  // Respond to link http://www.example.com/deeplink\n    </intent-filter>\n    <intent-filter>\n        <action android:name=\"android.intent.action.VIEW\" />\n        <category android:name=\"android.intent.category.DEFAULT\" />\n        <category android:name=\"android.intent.category.BROWSABLE\" />\n        <data android:scheme=\"app\"\n              android:host=\"deeplink.com\" />  // Respond to link app://deeplink\n    </intent-filter>\n</activity>" },
    { type: "paragraph", text: "You can also add more <data> tag to an intent filter. But, this makes your activity can handle all variations of their combined attribute." },
    { type: "heading", text: "Get Data From Intent" },
    { type: "paragraph", text: "Now, the activity can read data and action from the intent like this." },
    { type: "code", code: "override fun onCreate(savedInstanceState: Bundle?) {\n    super.onCreate(savedInstanceState)\n    setContentView(R.layout.main)\n\n    val action: String? = intent?.action\n    val data: Uri? = intent?.data\n}" },
    { type: "heading", text: "Android App Links" },
    { type: "paragraph", text: "Whit this special link, you can open your app using your link without any disambiguation dialog appear. To achieve that, you must be the owner of the website and (of course) the app." },
    { type: "heading", text: "Verify Your App" },
    { type: "paragraph", text: "You have to add **intent-filter** which has **android:autoVerify** attribute and set the value true. The rest of the intent filter is the same as the example in the previous section." },
    { type: "code", code: "<activity\n    android:name=\"com.example.deeplinkapp\"\n    >\n    <intent-filter android:autoVerify=\"true> // set autoVerify to true\n        <action android:name=\"android.intent.action.VIEW\" />\n        <category android:name=\"android.intent.category.DEFAULT\" />\n        <category android:name=\"android.intent.category.BROWSABLE\" />\n        <data android:scheme=\"http\"\n              android:host=\"www.example.com\"\n              android:path=\"/deeplink\" />\n    </intent-filter>\n</activity>" },
    { type: "heading", text: "Verify Your Website" },
    { type: "paragraph", text: "You have to **declare the association** between your intent filters by hosting a **Digital Asset Links JSON** file at the following location." },
    { type: "code", code: "https://domain.name/.well-known/assetlinks.json" },
    { type: "paragraph", text: "To get the JSON file, you can define the JSON by yourself or use App Link Assistant(Top Bar -> Tools -> App Link Assistant)." },
    { type: "image", src: "/assets/blog/deep-link-another-way-to-open-your-app/img-2.png" },
    { type: "paragraph", text: "App Link Assistant" },
    { type: "paragraph", text: "Using this tools, you can also define the intent filter easily. To create digital asset, click on the Open Digital Asset Links File Generator (3. Associate Website). Then, type your website and your app package id. If you use debug app, make sure to create the signed bundle/apk first. After that, click generate and you will get the JSON." },
    { type: "image", src: "/assets/blog/deep-link-another-way-to-open-your-app/img-3.png" },
    { type: "paragraph", text: "Digital Asset Links Generator" },
    { type: "code", code: "[{\n  \"relation\": [\"delegate_permission/common.handle_all_urls\"],\n  \"target\" : {\n    \"namespace\": \"android_app\",\n    \"package_name\": \"com.rizqi.deeplinkapp\",\n    \"sha256_cert_fingerprints\": [\"EB:90:00:93:F3:ED:FD:A1:D1:84:F6:42:B7:68:97:D4:EA:B9:7E:83:D7:2A:EF:5B:DA:5A:0B:13:9B:51:3B:11\"] }\n}]" },
    { type: "paragraph", text: "If the app already publish in Playstore, you can change or add more the SHA 256 fingerprint from the Google Play Console. Then, you have to save the JSON file and location that I mention before." },
    { type: "paragraph", text: "note: if you have a problem with the generator, you can use this [**website**](https://developers.google.com/digital-asset-links/tools/generator) to generate and test digital asset links." },
    { type: "heading", text: "Other Popular Scheme" },
    { type: "heading", text: "geo" },
    { type: "paragraph", text: "This scheme makes your intent-filter or app exists in disambiguation dialog for geolocation URI" },
    { type: "code", code: "<intent-filter android:priority=\"0\">\n    <action android:name=\"android.intent.action.VIEW\"/>\n    <category android:name=\"android.intent.category.DEFAULT\"/>\n    <category android:name=\"android.intent.category.BROWSABLE\"/>\n    <data android:scheme=\"geo\"/>\n</intent-filter>" },
    { type: "heading", text: "tel" },
    { type: "paragraph", text: "This scheme makes your intent-filter or app exists in disambiguation dialog for phone number URI" },
    { type: "code", code: "<intent-filter android:priority=\"0\">\n    <action android:name=\"android.intent.action.VIEW\"/>\n    <category android:name=\"android.intent.category.DEFAULT\"/>\n    <category android:name=\"android.intent.category.BROWSABLE\"/>\n    <data android:scheme=\"tel\"/>\n</intent-filter>" },
    { type: "heading", text: "mailto" },
    { type: "paragraph", text: "When user want to create email" },
    { type: "code", code: "<intent-filter android:priority=\"0\">\n    <action android:name=\"android.intent.action.VIEW\"/>\n    <category android:name=\"android.intent.category.DEFAULT\"/>\n    <category android:name=\"android.intent.category.BROWSABLE\"/>\n    <data android:scheme=\"mailto\"/>\n</intent-filter>" },
    { type: "heading", text: "References" },
    {
      type: "links",
      items: [
        { label: "Handling Android App Links | Android Developers", href: "https://developer.android.com/training/app-links" },
        { label: "<data> | Android Developers", href: "https://developer.android.com/guide/topics/manifest/data-element.html" },
      ],
    },
    { type: "paragraph", text: "I think that’s enough for this post. Thanks for reading my post. Follow to get more post about Android Development. Like if you find this helpful. Comment if you have something to ask, say hi, give thanks, or anything." },
  ],
};

export default deepLinkAnotherWayToOpenYourApp;
