import type { Post } from "../data";

const gettingStartedWithAugmentedRealityArInAndroid: Post = {
  slug: "getting-started-with-augmented-reality-ar-in-android",
  title: "Getting Started with Augmented Reality (AR) in Android",
  tag: "Android",
  date: "Mar 2023",
  readTime: "3 min read",
  excerpt: "Augmented Reality is a technology that overlays virtual elements in the real world, creating a blended environment that enhances the user’s experience. With the increasing popularity of AR, more and more developers are looking for ways to integrate this technology into their applications.",
  cover: "/assets/blog/getting-started-with-augmented-reality-ar-in-android/img-1.png",
  link: "https://medium.com/@mrizqi070502/getting-started-with-augmented-reality-ar-in-android-a42019e30f41",
  body: [
    { type: "paragraph", text: "Augmented Reality is a technology that overlays virtual elements in the real world, creating a blended environment that enhances the user’s experience. With the increasing popularity of AR, more and more developers are looking for ways to integrate this technology into their applications. In this post, we will implement basic AR using SceneView." },
    { type: "heading", text: "1️⃣Configure The Gradle" },
    { type: "paragraph", text: "Add the ArSceneView(part of SceneView) dependency in `app/build.gradle` . This dependency includes Filament and ARCore." },
    { type: "code", code: "// 3D and ARCore\nimplementation 'io.github.sceneview:arsceneview:0.9.7'" },
    { type: "paragraph", text: "The minimum Sdk version to use SceneView is 24, make sure you change it." },
    { type: "code", code: "defaultConfig {\n        ...\n        minSdk 24  // minSdk to use sceneview is 24\n        ...\n    }" },
    { type: "heading", text: "2️⃣Import Models" },
    { type: "paragraph", text: "The format supported by SceneView is `.glb` and `.gltf` . If you don’t have it, you can get the same as I used [**here](https://storage.googleapis.com/ar-answers-in-search-models/static/GiantPanda/model.glb).**" },
    { type: "paragraph", text: "Then, create `assets` directory inside `main` directory. Optionally, you can also create `models` directory inside the assets. Next, import your model into the directory by dragging or copy-paste it from your folder." },
    { type: "image", src: "/assets/blog/getting-started-with-augmented-reality-ar-in-android/img-1.png" },
    { type: "paragraph", text: "Directory for the model" },
    { type: "heading", text: "3️⃣Add ArSceneView to The Layout" },
    { type: "paragraph", text: "Add `ArSceneView` to your layout. This view will display the camera and place your 3D model on it." },
    { type: "code", code: "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<androidx.constraintlayout.widget.ConstraintLayout xmlns:android=\"http://schemas.android.com/apk/res/android\"\n    xmlns:app=\"http://schemas.android.com/apk/res-auto\"\n    xmlns:tools=\"http://schemas.android.com/tools\"\n    android:layout_width=\"match_parent\"\n    android:layout_height=\"match_parent\"\n    tools:context=\".MainActivity\">\n\n    <io.github.sceneview.ar.ArSceneView\n        android:id=\"@+id/arSceneView\"\n        android:layout_width=\"match_parent\"\n        android:layout_height=\"match_parent\" />\n\n</androidx.constraintlayout.widget.ConstraintLayout>" },
    { type: "heading", text: "4️⃣Create ArModelNode" },
    { type: "paragraph", text: "Create `ArModelNode` to define how the model’s placement, position, and anchor." },
    { type: "paragraph", text: "For the `placementMode` , there are" },
    { type: "paragraph", text: "`PlacementMode.INSTANT` : Quick placement" },
    { type: "paragraph", text: "`PlacementMode.DEPTH`: Accurate placement" },
    { type: "paragraph", text: "`PlacementMode.PLANE_HORIZONTAL`: Only on horizontal plane/walls" },
    { type: "paragraph", text: "`PlacementMode.PLANE_VERTICAL`: Only on vertical plane/walls" },
    { type: "paragraph", text: "`PlacementMode.PLANE_HORIZONTAL_AND_VERTICAL`: Only on both horizontal and vertical plane/walls" },
    { type: "paragraph", text: "`PlacementMode.BEST_AVAILABLE`: Auto refining accuracy placement" },
    { type: "paragraph", text: "`hitPosition` is the node camera/screen/view position where the hit will be made to find an AR position." },
    { type: "paragraph", text: "`followHitPosition` will make the node follow the camera/screen" },
    { type: "paragraph", text: "`instantAnchor` will anchor the node in the first suitable place." },
    { type: "code", code: "class MainActivity : AppCompatActivity() {\n\n    lateinit var arSceneView: ArSceneView\n    var modelNode : ArModelNode? = null\n\n    override fun onCreate(savedInstanceState: Bundle?) {\n        super.onCreate(savedInstanceState)\n        setContentView(R.layout.activity_main)\n\n        arSceneView = findViewById(R.id.arSceneView)\n\n        modelNode = ArModelNode(\n            placementMode = PlacementMode.BEST_AVAILABLE,\n            hitPosition = Position(x = 0.0f, y = 0.0f, z = -2.0f),\n            followHitPosition = true,\n            instantAnchor = true\n        )\n\n    }\n}" },
    { type: "heading", text: "5️⃣Load The Model" },
    { type: "paragraph", text: "Using the `ArModelNode` , we load the model from our assets by calling `loadModelGlbAsync()` because we use .glb format for the model. Or, if you want to load it within a Coroutine Scope, you can call `loadModel()` ." },
    { type: "paragraph", text: "You can also load the models from the internet by passing the link into `glbFileLocation` ." },
    { type: "paragraph", text: "`scaleToUnit` is used to scaling the model when it is loaded." },
    { type: "paragraph", text: "`centerOrigin` is the center point origin position within the model. The values are between -1.0 and 1.0 corresponding to the percents from model sizes." },
    { type: "code", code: "class MainActivity : AppCompatActivity() {\n\n    lateinit var arSceneView: ArSceneView\n    var modelNode : ArModelNode? = null\n\n    override fun onCreate(savedInstanceState: Bundle?) {\n        ...\n\n        modelNode = ArModelNode(...)\n\n        modelNode?.loadModelGlbAsync(\n            context = this@MainActivity,\n            glbFileLocation = \"models/panda.glb\",\n            autoAnimate = true,\n            scaleToUnits = 0.9f,\n            centerOrigin = Position(y = -1.0f),\n            onError = {exception ->\n                Toast.makeText(this, exception.message.toString(), Toast.LENGTH_SHORT).show()\n            },\n            onLoaded = {modelInstance ->\n\n            }\n        )\n\n    }\n}" },
    { type: "heading", text: "6️⃣Display The Model" },
    { type: "paragraph", text: "To display the loaded model, call `addChild()` method from `ArSceneView` by passing the model node." },
    { type: "code", code: "\nclass MainActivity : AppCompatActivity() {\n\n    lateinit var arSceneView: ArSceneView\n    var modelNode : ArModelNode? = null\n\n    override fun onCreate(savedInstanceState: Bundle?) {\n        ...\n\n        modelNode = ArModelNode(\n            ...\n        )\n\n        modelNode?.loadModelGlbAsync(\n            ...\n        )\n\n        modelNode?.let {\n            arSceneView.addChild(it)\n        }\n    }\n}" },
    { type: "heading", text: "Fullcode" },
    { type: "code", code: "package com.rizqi.ar\n\nimport androidx.appcompat.app.AppCompatActivity\nimport android.os.Bundle\nimport android.widget.Toast\nimport io.github.sceneview.ar.ArSceneView\nimport io.github.sceneview.ar.node.ArModelNode\nimport io.github.sceneview.ar.node.PlacementMode\nimport io.github.sceneview.math.Position\n\nclass MainActivity : AppCompatActivity() {\n\n    lateinit var arSceneView: ArSceneView\n    var modelNode : ArModelNode? = null\n\n    override fun onCreate(savedInstanceState: Bundle?) {\n        super.onCreate(savedInstanceState)\n        setContentView(R.layout.activity_main)\n\n        arSceneView = findViewById(R.id.arSceneView)\n\n        modelNode = ArModelNode(\n            placementMode = PlacementMode.BEST_AVAILABLE,\n            hitPosition = Position(x = 0.0f, y = 0.0f, z = -2.0f),\n            followHitPosition = true,\n            instantAnchor = true\n        )\n        modelNode?.loadModelGlbAsync(\n            context = this@MainActivity,\n            glbFileLocation = \"models/panda.glb\",\n            autoAnimate = true,\n            scaleToUnits = 0.9f,\n            centerOrigin = Position(y = -1.0f),\n            onError = {exception ->\n                Toast.makeText(this, exception.message.toString(), Toast.LENGTH_SHORT).show()\n            },\n            onLoaded = {modelInstance ->\n\n            }\n        )\n        modelNode?.let {\n            arSceneView.addChild(it)\n        }\n    }\n}" },
    { type: "heading", text: "Result" },
    { type: "image", src: "/assets/blog/getting-started-with-augmented-reality-ar-in-android/img-2.gif" },
    { type: "paragraph", text: "Result" },
    { type: "paragraph", text: "Yay 🎉, we just learn how to implement Augmented Reality (AR) in Android App. We successfully display the 3D model in the real world through our phone. For the recap, We need to create" },
    { type: "code", code: "ArModelNode" },
    { type: "paragraph", text: "to define the position configuration. Using the node, we load the model and display it into" },
    { type: "code", code: "ArSceneView" },
    { type: "paragraph", text: "." },
    { type: "paragraph", text: "Thanks for following this far. [**Follow me**](https://medium.com/@mrizqi070502/about) to get more about Android Development posts. Let’s connect on [**LinkedIn**](https://www.linkedin.com/in/m-rizqi/) and [**Instagram**](https://www.instagram.com/_riz.qi/)" },
    { type: "heading", text: "Reference" },
    {
      type: "links",
      items: [
        { label: "SceneView — Github", href: "https://github.com/SceneView/sceneview-android" },
        { label: "SceneView | 3D and AR View for Android, iOS and React Native (Android and iOS) working with ARCore/ARKit and Google Filament", href: "https://sceneview.github.io/api/sceneview-android/arsceneview/" },
      ],
    },
  ],
};

export default gettingStartedWithAugmentedRealityArInAndroid;
