import type { Post } from "../data";

const guideToAddingAdmobAdsToYourAndroidApp: Post = {
  slug: "guide-to-adding-admob-ads-to-your-android-app",
  title: "Guide To Adding AdMob Ads To Your Android App",
  tag: "Android",
  date: "Feb 2023",
  readTime: "6 min read",
  excerpt: "As a developer, monetizing your Android app is key to your success. One popular way to generate revenue is by incorporating AdMob, Google’s mobile advertising platform.",
  cover: "/assets/blog/guide-to-adding-admob-ads-to-your-android-app/img-1.png",
  link: "https://medium.com/@mrizqi070502/guide-to-adding-admob-ads-to-your-android-app-a72d07f44883",
  body: [
    { type: "paragraph", text: "As a developer, monetizing your Android app is key to your success. One popular way to generate revenue is by incorporating AdMob, Google’s mobile advertising platform. However, integrating AdMob into your app can be a challenging process, especially for those new to mobile development. In this guide, we will walk you through the process of adding AdMob ads to your Android app, from setting up an AdMob account to implementing ads within your app’s code. Whether you’re an experienced developer or just getting started, this guide will provide you with a comprehensive approach to monetizing your Android app with AdMob" },
    { type: "heading", text: "AdMob" },
    { type: "heading", text: "1️⃣Create AdMob Account" },
    { type: "paragraph", text: "Log in if you have an admob account or sign up if you don’t have one. [**Mobile App Monetization — Google AdMob**](https://admob.google.com/home/)" },
    { type: "heading", text: "2️⃣Register an App & Get the App ID" },
    { type: "paragraph", text: "On the home page, click the **App** menu in the sidebar. Then click **Add App**. Choose the **platform** for **Android.** Then choose if the app listens in the supported app store or not. For this example, I choose the no option." },
    { type: "image", src: "/assets/blog/guide-to-adding-admob-ads-to-your-android-app/img-1.png" },
    { type: "paragraph", text: "Set up a new app in admob. Step 1" },
    { type: "paragraph", text: "The next step is to fill in your **app name**. Lastly, click **Add App**." },
    { type: "image", src: "/assets/blog/guide-to-adding-admob-ads-to-your-android-app/img-2.png" },
    { type: "paragraph", text: "Set up a new app in AdMob. Step 2" },
    { type: "paragraph", text: "Now, go to the all apps list. There, you will get the AdMob app ID." },
    { type: "image", src: "/assets/blog/guide-to-adding-admob-ads-to-your-android-app/img-3.png" },
    { type: "paragraph", text: "AdMob App ID" },
    { type: "heading", text: "3️⃣Create Ad Unit" },
    { type: "paragraph", text: "The ad unit is the container to show the ads. It sends requests to AdMob and then displays the ad. There are many types of ad units and we need the ad unit id for our project." },
    { type: "paragraph", text: "In the sidebar, after we register an app. Go to the **Ad Units menu**. Click the **Ad Unit button** or **Get Started**(if you don’t have any ad units before). You will be given various options about the type of ad unit. Choose what you want and follow the step. Each unit may well have different steps, for example, Banner Ad just needs a name but Rewarded Ad also needs the amount and type of reward." },
    { type: "image", src: "/assets/blog/guide-to-adding-admob-ads-to-your-android-app/img-4.png" },
    { type: "paragraph", text: "Step to create ad unit" },
    { type: "paragraph", text: "After that, you will have the ad unit id. Save it for later." },
    { type: "heading", text: "Don’t use the ad unit id while you building and testing the ads. Because your account will be suspended if you do that." },
    { type: "paragraph", text: "Always use AdMob’s dedicated test ad unit ID. Different types of the ad will have different test ad unit IDs. If you want to publish the app, you can replace it with your id." },
    { type: "image", src: "/assets/blog/guide-to-adding-admob-ads-to-your-android-app/img-5.png" },
    { type: "paragraph", text: "Ad Unit Id" },
    { type: "heading", text: "Android" },
    { type: "heading", text: "Get Started" },
    { type: "paragraph", text: "First, include [Google’s Maven repository](https://maven.google.com/web/index.html) and [Maven central repository](https://search.maven.org/artifact) in `buildscript` and `all/project` sections" },
    { type: "code", code: "buildscript {\n    repositories {\n        google()\n        mavenCentral()\n    }\n}\n\nallprojects {\n    repositories {\n        google()\n        mavenCentral()\n    }\n}" },
    { type: "paragraph", text: "Then, add Google Mobile Ads SDK dependency into app-level module `app/build.gradle`" },
    { type: "code", code: "dependencies {\n  implementation 'com.google.android.gms:play-services-ads:21.5.0'\n}" },
    { type: "paragraph", text: "Next, add metadata in `AndroidManifest.xml` about AdMob app ID." },
    { type: "code", code: "<manifest>\n    <application>\n        <meta-data\n            android:name=\"com.google.android.gms.ads.APPLICATION_ID\"\n            android:value=\"ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy\"/> // Replace with your AdMob app ID\n    </application>\n</manifest>" },
    { type: "paragraph", text: "For this guide, I will show how to implement 4 Ad Format" },
    { type: "heading", text: "1️⃣Banner Ad" },
    { type: "paragraph", text: "A banner advertisement takes up a specific area of an application’s design, positioned either at the top or bottom of the screen. The ad remains visible even as users engage with the application, and it may refresh itself automatically after a set interval. For those who are unfamiliar with mobile advertising, banners are an excellent entry point." },
    { type: "heading", text: "Place AdView within the layout" },
    { type: "code", code: "<com.google.android.gms.ads.AdView\n        android:id=\"@+id/bannerAdView\"\n        xmlns:ads=\"http://schemas.android.com/apk/res-auto\"\n        android:layout_width=\"wrap_content\"\n        android:layout_height=\"wrap_content\"\n        ads:layout_constraintBottom_toBottomOf=\"parent\"\n        ads:layout_constraintStart_toStartOf=\"parent\"\n        ads:layout_constraintEnd_toEndOf=\"parent\"\n        ads:adSize=\"BANNER\"\n        ads:adUnitId=\"ca-app-pub-3940256099942544/6300978111\"\n        />" },
    { type: "paragraph", text: "for the `adSize` attribute, several contents describe the size of the banner(widthxheight). Some of those are" },
    { type: "paragraph", text: "**BANNER** : 320x50 dp" },
    { type: "paragraph", text: "**LARGE_BANNER** : 320x100 dp" },
    { type: "paragraph", text: "**FULL_BANNER** : 468x60 dp" },
    { type: "paragraph", text: "full list of constants can be seen [**here**](https://developers.google.com/admob/android/banner#banner_sizes)" },
    { type: "paragraph", text: "For the `adUnitId` attribute, replace it with your banner ad unit id that you created before in the AdMob dashboard. But, if you are still in developing or testing replace it with the test ad unit id. It is" },
    { type: "paragraph", text: "`ca-app-pub-3940256099942544/6300978111`" },
    { type: "heading", text: "Load an Ad" },
    { type: "paragraph", text: "To load an Ad, you need to initialize `MobileAds` and create `AdRequest`" },
    { type: "code", code: "class MainActivity : AppCompatActivity() {\n    lateinit var bannerAdView : AdView\n\n    override fun onCreate(savedInstanceState: Bundle?) {\n        super.onCreate(savedInstanceState)\n        setContentView(R.layout.activity_main)\n\n        MobileAds.initialize(this)\n\n        bannerAdView = findViewById(R.id.bannerAdView)\n\n        val adRequest = AdRequest.Builder().build()\n\n        // Banner\n        bannerAdView.loadAd(adRequest)\n    }\n}" },
    { type: "heading", text: "Listen to Ad Events" },
    { type: "paragraph", text: "You can listen to ad events such as when the ad loaded, clicked, opened, etc using `AdListener`" },
    { type: "code", code: "bannerAdView.adListener = object : AdListener(){\n            override fun onAdClicked() {\n                super.onAdClicked()\n                Toast.makeText(this@MainActivity, \"Banner Ad Clicked\", Toast.LENGTH_SHORT).show()\n            }\n\n            override fun onAdClosed() {\n                super.onAdClosed()\n                Toast.makeText(this@MainActivity, \"Banner Ad Closed\", Toast.LENGTH_SHORT).show()\n            }\n\n            override fun onAdFailedToLoad(p0: LoadAdError) {\n                super.onAdFailedToLoad(p0)\n                Toast.makeText(this@MainActivity, \"Banner Ad Failed To Load\", Toast.LENGTH_SHORT).show()\n            }\n\n            override fun onAdImpression() {\n                super.onAdImpression()\n                Toast.makeText(this@MainActivity, \"Banner Ad Impression\", Toast.LENGTH_SHORT).show()\n            }\n\n            override fun onAdLoaded() {\n                super.onAdLoaded()\n                Toast.makeText(this@MainActivity, \"Banner Ad Loaded\", Toast.LENGTH_SHORT).show()\n            }\n\n            override fun onAdOpened() {\n                super.onAdOpened()\n                Toast.makeText(this@MainActivity, \"Banner Ad Opened\", Toast.LENGTH_SHORT).show()\n            }\n\n            override fun onAdSwipeGestureClicked() {\n                super.onAdSwipeGestureClicked()\n                Toast.makeText(this@MainActivity, \"Banner Ad Swipe Gesture Clicked\", Toast.LENGTH_SHORT).show()\n            }\n        }" },
    { type: "heading", text: "Enable Hardware Acceleration" },
    { type: "paragraph", text: "Some of the ads are video. To show it successfully, you can accelerate the hardware using `android:hardwareAccelerated` attribute in your `application` or `activity` tag in your manifest." },
    { type: "code", code: "<activity\n    android:name=\".MainActivity\"\n    android:exported=\"true\"\n    android:hardwareAccelerated=\"true\">\n\n    ....\n\n</activity>" },
    { type: "image", src: "/assets/blog/guide-to-adding-admob-ads-to-your-android-app/img-6.jpeg" },
    { type: "paragraph", text: "Banner Ad" },
    { type: "heading", text: "2️⃣Interstitial Ad" },
    { type: "paragraph", text: "Interstitial advertisements are ads that fill the entire screen, concealing the interface of the app they’re hosted in. These types of ads are usually presented at logical break points in the application’s flow, such as during transitions between activities or when pausing between levels in a game. If an app shows an interstitial ad, the user can either click on the ad and proceed to its destination or dismiss it and return to the application." },
    { type: "heading", text: "Load an Ad" },
    { type: "paragraph", text: "Interstitial Ad doesn’t need a view in the layout. So, we can just load the ad and show it later. Using `InterstitialAd` class to `load()` while passing `AdRequest` and `InterstitialAdLoadCallback` into the parameter." },
    { type: "code", code: "class MainActivity : AppCompatActivity() {\n\n    ...\n    lateinit var startInterstitialAdButton : MaterialButton\n    var mInterstitialAd: InterstitialAd? = null\n\n    override fun onCreate(savedInstanceState: Bundle?) {\n        super.onCreate(savedInstanceState)\n        setContentView(R.layout.activity_main)\n\n        startInterstitialAdButton = findViewById(R.id.startInterstitialAdButton)\n\n        val adRequest = AdRequest.Builder().build()\n\n        ...\n\n        //Interstitial\n        InterstitialAd.load(\n            this,\n            \"ca-app-pub-3940256099942544/1033173712\",\n            adRequest,\n            object : InterstitialAdLoadCallback(){\n                override fun onAdFailedToLoad(p0: LoadAdError) {\n                    Toast.makeText(this@MainActivity, \"Interstitial Ad Failed To Load\", Toast.LENGTH_SHORT).show()\n                    mInterstitialAd = null\n                }\n\n                override fun onAdLoaded(interstitialAd: InterstitialAd) {\n                    Toast.makeText(this@MainActivity, \"Interstitial Ad Failed Loaded\", Toast.LENGTH_SHORT).show()\n                    mInterstitialAd = interstitialAd\n                }\n            }\n        )\n\n    }\n}" },
    { type: "paragraph", text: "The test ad unit ID for Interstitial Ad is" },
    { type: "paragraph", text: "`ca-app-pub-3940256099942544/1033173712`" },
    { type: "heading", text: "Set the `FullScreenContentCallback`" },
    { type: "paragraph", text: "You can observe and handle the ad events using this callback. There are bunch of method that you can override" },
    { type: "code", code: "mInterstitialAd?.fullScreenContentCallback = object : FullScreenContentCallback(){\n            override fun onAdClicked() {\n                Toast.makeText(this@MainActivity, \"Interstitial Ad Clicked\", Toast.LENGTH_SHORT).show()\n            }\n\n            override fun onAdDismissedFullScreenContent() {\n                Toast.makeText(this@MainActivity, \"Interstitial Dismissed Fullscreen Content\", Toast.LENGTH_SHORT).show()\n            }\n\n            override fun onAdFailedToShowFullScreenContent(p0: AdError) {\n                Toast.makeText(this@MainActivity, \"Interstitial Ad Failed To Show Full Screen Content\", Toast.LENGTH_SHORT).show()\n            }\n\n            override fun onAdImpression() {\n                Toast.makeText(this@MainActivity, \"Interstitial Ad Impression\", Toast.LENGTH_SHORT).show()\n            }\n\n            override fun onAdShowedFullScreenContent() {\n                Toast.makeText(this@MainActivity, \"Interstitial Ad Showed Fullscreen Content\", Toast.LENGTH_SHORT).show()\n            }\n        }" },
    { type: "heading", text: "Show the Ad" },
    { type: "paragraph", text: "Call `show()` method from `InterstitialAd` to show the ad." },
    { type: "code", code: "startInterstitialAdButton.setOnClickListener {\n            mInterstitialAd?.show(this)\n        }" },
    { type: "image", src: "/assets/blog/guide-to-adding-admob-ads-to-your-android-app/img-7.gif" },
    { type: "paragraph", text: "Interstitial Ad" },
    { type: "heading", text: "3️⃣Native Ad" },
    { type: "paragraph", text: "Native advertisements are advertising materials that are displayed to users by utilizing UI components that are native to the particular platform. These ads are exhibited by utilizing the same types of views that are already utilized to build layouts, and can be customized to blend in with the visual design of the user experience in which they appear." },
    { type: "heading", text: "Load an Ad" },
    { type: "paragraph", text: "We need to build an `AdLoader` to load the ad." },
    { type: "paragraph", text: "The test ad id for Native Ad is" },
    { type: "paragraph", text: "`ca-app-pub-3940256099942544/2247696110`" },
    { type: "code", code: "class MainActivity : AppCompatActivity() {\n    ...\n\n    override fun onCreate(savedInstanceState: Bundle?) {\n        super.onCreate(savedInstanceState)\n        setContentView(R.layout.activity_main)\n\n        ...\n\n        //Native\n        val adLoader : AdLoader = AdLoader.Builder(this, \"ca-app-pub-3940256099942544/2247696110\")\n            .forNativeAd { nativeAd : NativeAd ->\n                // To display the ad\n            }\n            .build()\n\n    }\n}" },
    { type: "paragraph", text: "Also, if you want. You can set up `AdListener` in `AdLoader`" },
    { type: "code", code: "//Native\n        val adLoader : AdLoader = AdLoader.Builder(this, \"ca-app-pub-3940256099942544/2247696110\")\n            .forNativeAd { nativeAd : NativeAd ->\n                // To display the ad\n            }\n            .withAdListener(object : AdListener() {\n                override fun onAdClicked() {\n                    Toast.makeText(this@MainActivity, \"Native ad clicked\", Toast.LENGTH_SHORT).show()\n                }\n\n                override fun onAdClosed() {\n                    Toast.makeText(this@MainActivity, \"Native ad closed\", Toast.LENGTH_SHORT).show()\n                }\n\n                override fun onAdFailedToLoad(p0: LoadAdError) {\n                    Toast.makeText(this@MainActivity, \"Native ad failed to load\", Toast.LENGTH_SHORT).show()\n                }\n\n                override fun onAdImpression() {\n                    Toast.makeText(this@MainActivity, \"Native ad impression\", Toast.LENGTH_SHORT).show()\n                }\n\n                override fun onAdLoaded() {\n                    Toast.makeText(this@MainActivity, \"Native ad loaded\", Toast.LENGTH_SHORT).show()\n                }\n\n                override fun onAdOpened() {\n                    Toast.makeText(this@MainActivity, \"Native ad opened\", Toast.LENGTH_SHORT).show()\n                }\n\n                override fun onAdSwipeGestureClicked() {\n                    Toast.makeText(this@MainActivity, \"Native ad swipe gesture clicked\", Toast.LENGTH_SHORT).show()\n                }\n            })\n            .withNativeAdOptions(NativeAdOptions.Builder().build())\n            .build()" },
    { type: "paragraph", text: "Then load the ad using `AdLoader`" },
    { type: "code", code: "adLoader.loadAd(AdRequest.Builder().build())" },
    { type: "paragraph", text: "Or, if you want to load multiple ads, you can send the request like this" },
    { type: "code", code: "adLoader.loadAds(AdRequest.Builder().build(), 3)  // load 3 ads" },
    { type: "heading", text: "Set the Layout" },
    { type: "paragraph", text: "Regarding the NativeAd format, there exists a corresponding `NativeAdView`class that publishers ought to utilize as the foundation for the `NativeAd`. The `NativeAdView`class is a `ViewGroup` so you can create the layout more flexibly." },
    { type: "paragraph", text: "For this example, I just the headline, app icon, and content of the app inside the `NativeAdView` ." },
    { type: "code", code: "<com.google.android.gms.ads.nativead.NativeAdView\n        android:id=\"@+id/nativeAdView\"\n        android:layout_width=\"match_parent\"\n        android:layout_height=\"0dp\"\n        app:layout_constraintTop_toTopOf=\"parent\"\n        android:layout_marginBottom=\"16dp\"\n        android:visibility=\"visible\"\n        >\n\n        <RelativeLayout\n            android:layout_width=\"match_parent\"\n            android:layout_height=\"match_parent\"\n            >\n\n            <com.google.android.gms.ads.nativead.MediaView\n                android:id=\"@+id/nativeAdMediaView\"\n                android:layout_width=\"match_parent\"\n                android:layout_height=\"match_parent\"\n                android:layout_marginBottom=\"16dp\"\n                />\n\n            <LinearLayout\n                android:layout_width=\"wrap_content\"\n                android:layout_height=\"wrap_content\"\n                android:layout_alignParentTop=\"true\"\n                android:layout_alignParentStart=\"true\"\n                android:orientation=\"horizontal\"\n                >\n\n                <ImageView\n                    android:id=\"@+id/nativeAdAppIcon\"\n                    android:layout_width=\"wrap_content\"\n                    android:layout_height=\"wrap_content\"\n                    />\n\n                <TextView\n                    android:id=\"@+id/nativeAdHeadline\"\n                    android:layout_width=\"wrap_content\"\n                    android:layout_height=\"wrap_content\"\n                    android:layout_marginStart=\"16dp\"\n                    />\n\n            </LinearLayout>\n\n        </RelativeLayout>\n\n    </com.google.android.gms.ads.nativead.NativeAdView>" },
    { type: "heading", text: "Display the Ad" },
    { type: "paragraph", text: "Now, we need to assign the value to the headline, app icon, and content in the layout." },
    { type: "code", code: "val adLoader : AdLoader = AdLoader.Builder(this, \"ca-app-pub-3940256099942544/2247696110\")\n            .forNativeAd { nativeAd : NativeAd ->\n                if (this.isDestroyed){\n                    nativeAd.destroy()\n                    return@forNativeAd\n                }\n\n                val adView = findViewById<NativeAdView>(R.id.nativeAdView)\n                val headlineTextView = findViewById<TextView>(R.id.nativeAdHeadline)\n                val iconImageView = findViewById<ImageView>(R.id.nativeAdAppIcon)\n                val adMediaView = findViewById<MediaView>(R.id.nativeAdMediaView)\n\n                headlineTextView.text = nativeAd.headline\n                iconImageView.setImageURI(nativeAd.icon?.uri)\n                adMediaView.mediaContent = nativeAd.mediaContent\n                adMediaView.setImageScaleType(ImageView.ScaleType.CENTER_CROP)\n                adView.setNativeAd(nativeAd)\n            }\n..." },
    { type: "image", src: "/assets/blog/guide-to-adding-admob-ads-to-your-android-app/img-8.jpeg" },
    { type: "paragraph", text: "Native Ad" },
    { type: "heading", text: "4️⃣Rewarded Ad" },
    { type: "paragraph", text: "Rewarded advertisements are a well-liked type of advertisement that offers users the chance to view a video or interact with an interactive ad, and in return, receive a reward within the application." },
    { type: "heading", text: "Load an Ad" },
    { type: "paragraph", text: "Quite similar to Interstitial Ad, We load the add using`RewaredAd` class and calling `load()` method and passing some parameters. Those are context, ad unit id, ad request, and `RewardedAdLoadCallback` ." },
    { type: "paragraph", text: "The test id for Rewarded Ad is" },
    { type: "paragraph", text: "`ca-app-pub-3940256099942544/5224354917`" },
    { type: "code", code: "class MainActivity : AppCompatActivity() {\n    ...\n    var rewardedAd : RewardedAd? = null\n\n    override fun onCreate(savedInstanceState: Bundle?) {\n        super.onCreate(savedInstanceState)\n        setContentView(R.layout.activity_main)\n\n        startRewardedAdButton = findViewById(R.id.startRewardedAdButton)\n\n        val adRequest = AdRequest.Builder().build()\n\n        //Rewarded\n        RewardedAd.load(\n            this,\n            \"ca-app-pub-3940256099942544/5224354917\",\n            adRequest,\n            object : RewardedAdLoadCallback() {\n                override fun onAdFailedToLoad(p0: LoadAdError) {\n                    Toast.makeText(this@MainActivity, \"Rewarded ad failed to load\", Toast.LENGTH_SHORT).show()\n                }\n\n                override fun onAdLoaded(ad: RewardedAd) {\n                    Toast.makeText(this@MainActivity, \"Rewarded ad loaded\", Toast.LENGTH_SHORT).show()\n                    rewardedAd = ad\n                }\n            }\n        )\n\n    }\n}" },
    { type: "heading", text: "Set the `FullScreenContentCallback`" },
    { type: "paragraph", text: "If you want to handle the events, you can set `FullScreenContentCallback` into `RewardedAd` object." },
    { type: "code", code: "rewardedAd?.fullScreenContentCallback = object : FullScreenContentCallback(){\n            override fun onAdClicked() {\n                Toast.makeText(this@MainActivity, \"Rewarded Ad Clicked\", Toast.LENGTH_SHORT).show()\n            }\n\n            override fun onAdDismissedFullScreenContent() {\n                Toast.makeText(this@MainActivity, \"Rewarded Dismissed Fullscreen Content\", Toast.LENGTH_SHORT).show()\n            }\n\n            override fun onAdFailedToShowFullScreenContent(p0: AdError) {\n                Toast.makeText(this@MainActivity, \"Rewarded Ad Failed To Show Full Screen Content\", Toast.LENGTH_SHORT).show()\n            }\n\n            override fun onAdImpression() {\n                Toast.makeText(this@MainActivity, \"Rewarded Ad Impression\", Toast.LENGTH_SHORT).show()\n            }\n\n            override fun onAdShowedFullScreenContent() {\n                Toast.makeText(this@MainActivity, \"Rewarded Ad Showed Fullscreen Content\", Toast.LENGTH_SHORT).show()\n            }\n        }" },
    { type: "heading", text: "Show the Ad" },
    { type: "paragraph", text: "Call `show()` method from `RewardedAd` and set `OnUserEarnedRewardListener` so you can know what reward item that user got." },
    { type: "code", code: "startRewardedAdButton.setOnClickListener {\n            rewardedAd?.let { ad ->\n                ad.show(this, OnUserEarnedRewardListener { rewardItem ->\n                    val rewardAmount = rewardItem.amount\n                    val rewardType = rewardItem.type\n                    Toast.makeText(this, \"You get $rewardAmount of $rewardType\", Toast.LENGTH_SHORT).show()\n                })\n            }\n        }" },
    { type: "image", src: "/assets/blog/guide-to-adding-admob-ads-to-your-android-app/img-9.jpeg" },
    { type: "paragraph", text: "Rewarded Ad" },
    { type: "paragraph", text: "Yay 🎉, you just learn how to add AdMob Ads to your Android App. Thanks for following this far. [**Follow me**](https://medium.com/@mrizqi070502/about) to get more about Android Development posts. Let’s connect on [**LinkedIn**](https://www.linkedin.com/in/m-rizqi/) and [**Instagram**](https://www.instagram.com/_riz.qi/)" },
    { type: "heading", text: "Reference" },
    {
      type: "links",
      items: [
        { label: "Ad units, ad formats, & ad types — Google AdMob Help", href: "https://support.google.com/admob/answer/6128738?hl=en" },
        { label: "Get Started | Android | Google Developers", href: "https://developers.google.com/admob/android/quick-start#kotlin" },
        { label: "https://developers.google.com/admob/android/banner#banner_sizes", href: "https://developers.google.com/admob/android/banner#banner_sizes" },
      ],
    },
  ],
};

export default guideToAddingAdmobAdsToYourAndroidApp;
