import type { Post } from "../data";

const implementasiDependencyInjectionPadaRoomDatabaseDanRet: Post = {
  slug: "implementasi-dependency-injection-pada-room-database-dan",
  title: "Implementasi Dependency Injection Pada Room Database dan Retrofit",
  tag: "Android",
  date: "Dec 2022",
  readTime: "3 min read",
  excerpt: "Pada postingan sebelumnya, saya menjelaskan mengenai bagaimana konsep dependency injection digunakan untuk memudahkan pengembangan aplikasi android.",
  cover: undefined,
  link: "https://medium.com/@mrizqi070502/implementasi-dependency-injection-pada-room-database-danrofit-6f87a201d82a",
  body: [
    { type: "paragraph", text: "Pada postingan sebelumnya, saya menjelaskan mengenai bagaimana konsep dependency injection digunakan untuk memudahkan pengembangan aplikasi android." },
    {
      type: "links",
      items: [
        { label: "Hilt Dependency Injection dalam Pengembangan Android", href: "https://medium.com/@mrizqi070502/hilt-dependency-injection-untuk-pengembangan-android-f97d2d710888" },
      ],
    },
    { type: "paragraph", text: "Kali ini saya akan membagikan pengalaman saya mengenai penggunaan dependency injection khususnya library Hilt." },
    { type: "heading", text: "Room Database" },
    { type: "paragraph", text: "Dalam beberapa kasus, aplikasi kita membutuhkan database local untuk menyimpan data. Untuk mendukung kebutuhan tersebut, terdapat fitur dari Android yang bernama Room. Berdasarkan dokumentasi dari website resmi [Android Developer](https://developer.android.com/jetpack/androidx/releases/room?hl=id), Room adalah Library persistensi yang memberikan lapisan abstraksi pada SQLite untuk memungkinkan akses database yang lebih stabil sambil memanfaatkan kemampuan penuh SQLite. Dalam kaitannya dengan arsitektur MVVM (Model-View-ViewModel), implementasi Room biasanya terdiri dari Entity atau Model, Dao, Room Database, Repository, ViewModel, dan View. Entity adalah class yang merepresentasikan objek yang ingin disimpan. Dao adalah interface yang mendefinisikan fungsi apa saja yang bisa dilakukan terkait database. RoomDatabase menyediakan instansiasi dari database dan dao. Repository bisa dikatakan sebagai jembatan tambahan untuk memenuhi konsep Single Source Of Truth. ViewModel sebagaimana yang sudah diketahui sebagai penghubung antara view dan data. Dan View adalah tampilan aplikasi itu sendiri." },
    { type: "paragraph", text: "Dari semua komponen MVVM tersebut, pada dasarnya dibutuhkan instansiasi dari Room Database. Akan tetapi, instansiasi dari Room Database membutuhkan context dari aplikasi. Ini artinya, di setiap Activity yang membutuhkan koneksi ke database harus membuat instance baru lagi. Tetap jangan khawatir karena dengan adanya Hilt, kita bisa menghindari hal membosankan tersebut." },
    { type: "paragraph", text: "Sebagai contoh, ingin dibuat database yang menyimpan data User, maka sebelum mengimplementasikan Dependency Injection kira-kira kodenya akan seperti ini." },
    { type: "paragraph", text: "*User.kt*" },
    { type: "code", code: "import androidx.room.Entity\n\n@Entity\ndata class User(\n    val name : String,\n    val email : String\n)" },
    { type: "paragraph", text: "*UserDao.kt*" },
    { type: "code", code: "import androidx.room.Dao\nimport androidx.room.Insert\nimport androidx.room.Query\n\n@Dao\ninterface UserDao {\n    \n    @Insert\n    suspend fun insertUser(user: User)\n    \n    @Query(\"SELECT * FROM User\")\n    fun getUsers() : List<User>\n    \n    // Other function to query database\n}" },
    { type: "paragraph", text: "*AppDatabase.kt*" },
    { type: "code", code: "import android.content.Context\nimport androidx.room.Database\nimport androidx.room.Room\nimport androidx.room.RoomDatabase\n\n@Database(\n    entities = [User::class],\n    version = 1\n)\nabstract class AppDatabase : RoomDatabase(){\n    abstract fun userDao() : UserDao\n    \n    companion object {\n        @Volatile\n        private var INSTANCE : AppDatabase? = null\n        fun getDatabase(context: Context) : AppDatabase {\n            return INSTANCE ?: synchronized(this){\n                val instance =  Room.databaseBuilder(\n                    context.applicationContext,\n                    AppDatabase::class.java,\n                    \"app_database\"\n                )\n                    .build()\n                INSTANCE = instance\n                return instance\n            }\n        }\n    }\n}" },
    { type: "paragraph", text: "*UserRepository.kt*" },
    { type: "code", code: "class UserRepository (appDatabase: AppDatabase) {\n    private val userDao = appDatabase.userDao()\n    suspend fun insertUser(user: User) = userDao.insertUser(user)\n    fun getUsers() = userDao.getUsers()\n}" },
    { type: "paragraph", text: "*ViewModel.kt*" },
    { type: "code", code: "import androidx.lifecycle.ViewModel\nimport androidx.lifecycle.viewModelScope\nimport kotlinx.coroutines.launch\n\nclass UserViewModel(\n    appDatabase: AppDatabase\n) : ViewModel(){\n    private val userRepository = UserRepository(appDatabase)\n    fun insertUser(user: User){\n        viewModelScope.launch { userRepository.insertUser(user) }\n    }\n    fun getUsers() = userRepository.getUsers()\n}" },
    { type: "paragraph", text: "dan pada Activity contohnya seperti berikut" },
    { type: "code", code: "@AndroidEntryPoint\nclass MainActivity : AppCompatActivity() {\n    override fun onCreate(savedInstanceState: Bundle?) {\n        super.onCreate(savedInstanceState)\n        setContentView(R.layout.activity_main)\n        val userViewModel = ViewModelProvider(this, ViewModelFactory(AppDatabase.getDatabase(this))).get(UserViewModel::class.java)\n    }\n}\n\nclass ViewModelFactory(private val appDatabase: AppDatabase) : ViewModelProvider.Factory {\n    @Suppress(\"unchecked_cast\")\n    override fun <T : ViewModel> create(modelClass: Class<T>): T {\n        if (modelClass.isAssignableFrom(UserViewModel::class.java)) {\n            return UserViewModel(appDatabase) as T\n        }\n        throw IllegalArgumentException(\"Unknown ViewModel class\")\n    }\n}" },
    { type: "paragraph", text: "Terlihat pada Acitvity dan juga ViewModelFactory yang membutuhkan instance dari RoomDatabase, selain itu jika ada banyak ViewModel maka pada ViewModelFactory juga perlu ditambahkan pengecekan dan instansiasi yang melelahkan." },
    { type: "quote", text: "We don’t do that here" },
    { type: "paragraph", text: "Lalu, bagaimana pendekatan dengan dependency injection ? Sama halnya dengan contoh kode di atas, kita tetap mendefinisikan komponen yang dibutuhkan pada constructor, hanya saja kita tambahkan anotasi Inject. Tentunya, kita juga harus memberitahu Hilt bagaimana cara menginstansiasi Room Database dengan membuat fungsinya di AppModule. Kemudian, pada pendekatan ini, kita tidak membutuhkan lagi ViewModelFactory karena kita bisa menggunakan fitur delegasi dari viewmodel. Sehingga kode dengan pendekatan dependency injection akan seperti ini." },
    { type: "paragraph", text: "*User.kt* dan *UserDao.kt* tetap sama seperti sebelumnya." },
    { type: "paragraph", text: "*AppDatabase.kt*" },
    { type: "code", code: "@Database(\n    entities = [User::class],\n    version = 1\n)\nabstract class AppDatabase : RoomDatabase(){\n    abstract fun userDao() : UserDao\n}" },
    { type: "paragraph", text: "*UserRepository.kt*" },
    { type: "code", code: "class UserRepository @Inject constructor(appDatabase: AppDatabase) {\n    private val userDao = appDatabase.userDao()\n    suspend fun insertUser(user: User) = userDao.insertUser(user)\n    fun getUsers() = userDao.getUsers()\n}" },
    { type: "paragraph", text: "*UserViewModel.kt*" },
    { type: "code", code: "@HiltViewModel\nclass UserViewModel @Inject constructor(\n    private val userRepository: UserRepository\n) : ViewModel(){\n    fun insertUser(user: User){\n        viewModelScope.launch { userRepository.insertUser(user) }\n    }\n    fun getUsers() = userRepository.getUsers()\n}" },
    { type: "paragraph", text: "*AppModule.kt*" },
    { type: "code", code: "@Module\n@InstallIn(SingletonComponent::class)\nobject AppModule {\n    @Provides\n    @Singleton\n    fun provideDatabase(@ApplicationContext context: Context) : AppDatabase {\n        return Room.databaseBuilder(\n            context.applicationContext,\n            AppDatabase::class.java,\n            \"app_database\"\n        ).build()\n    }\n}" },
    { type: "paragraph", text: "dan pada Activity" },
    { type: "code", code: "@AndroidEntryPoint\nclass MainActivity : AppCompatActivity() {\n    private val userViewModel : UserViewModel by viewModels()  \n    override fun onCreate(savedInstanceState: Bundle?) {\n        super.onCreate(savedInstanceState)\n        setContentView(R.layout.activity_main)\n    }\n}" },
    { type: "paragraph", text: "Terlihat lebih simple dan clean kan ✨. Dan juga singleton pada database tetap bisa dilakukan dengan menggunakan anotasi @Singleton pada fungsi di AppModule. Untuk parameter context yang digunakan pada instansiasi database bisa menggunakan ApplicationContext. Masukkan saja parameter pada fungsi di AppModule untuk context dan beri anotasi @ApplicationContext maka Hilt akan memberikan otomatis context dari aplikasi." },
    { type: "heading", text: "Retrofit" },
    { type: "paragraph", text: "Retrofit adalah network library yang digunakan untuk pemanggilan API. Sama seperti dengan Room Database, bagian yang di-inject adalah retrofit itu sendiri. Sisanya seperti ApiService, ViewModel, dan berbagai kebutuhan untuk melakukan pemanggilan api tetap sama sebagaimana biasanya. Contoh penyediaan instance dari retrofit adalah sebagai berikut." },
    { type: "code", code: "@Module\n@InstallIn(SingletonComponent::class)\nobject AppModule {\n    @Provides\n    @Singleton\n    fun provideDatabase(@ApplicationContext context: Context) : AppDatabase {\n        return Room.databaseBuilder(\n            context.applicationContext,\n            AppDatabase::class.java,\n            \"app_database\"\n        ).build()\n    }\n\n    @Provides\n    @Singleton\n    fun provideRetrofit(@ApplicationContext context: Context) : Retrofit {\n        return Retrofit.Builder()\n            .addConverterFactory(GsonConverterFactory.create())\n            .baseUrl(\"yourbaseurl.com\")\n            .build()\n    }\n}" },
    { type: "paragraph", text: "Itu tadi adalah cara menerapkan dependency injection jika kita menggunakan Room Database dan Retrofit pada projek yang dibuat. Semua yang dicontohkan diatas didasarkan dari pengalaman pribadi. Kalo ada yang kurang atau salah, feel free buat comment yaa. Thanks udah baca postingan ini. See you in the next post ….." },
  ],
};

export default implementasiDependencyInjectionPadaRoomDatabaseDanRet;
