import type { Post } from "../data";

const introductionToServicesInAndroid: Post = {
  slug: "introduction-to-services-in-android",
  title: "Introduction to Services in Android",
  tag: "Android",
  date: "Jan 2023",
  readTime: "3 min read",
  excerpt: "Have you ever wondered how the music player app can play music even though you minimize the app and show the notification about the music in real-time? Well, that can be approached using Service. But, what actual service is? Imagine service like something that offers you to do some kind of job.",
  cover: "/assets/blog/introduction-to-services-in-android/img-1.png",
  link: "https://medium.com/@mrizqi070502/introduction-to-services-in-android-657027627d0f",
  body: [
    { type: "paragraph", text: "Have you ever wondered how the music player app can play music even though you minimize the app and show the notification about the music in real-time? Well, that can be approached using Service. But, what actual service is? Imagine service like something that offers you to do some kind of job. According to the android developer docs," },
    { type: "quote", text: "A Service is an application component that can perform long-running operations in the background." },
    { type: "paragraph", text: "Different from activity and fragment (which is also called application component), the service doesn’t provide a user interface." },
    { type: "heading", text: "Types of Services" },
    { type: "heading", text: "Foreground" },
    { type: "paragraph", text: "When the app started the foreground service, the user will be noticed by displaying a Notification. This service will continue until either user stops or app removed the service. Therefore, this kind of service is rarely killed by the system." },
    { type: "heading", text: "Background" },
    { type: "paragraph", text: "This service is the opposite of foreground, the user will not be noticed and is highly susceptible to being killed by the system" },
    { type: "heading", text: "Bound" },
    { type: "paragraph", text: "Service called bound when there are one or more application components bound to it like sending and requesting data from each other. Service will be killed if there are no application components bound to it anymore." },
    { type: "heading", text: "How To #Create Service Class" },
    { type: "paragraph", text: "First, you need to define the class that will handle the operation. This class should extend the Service class. Once you extended it, you will need to override some of the methods." },
    { type: "code", code: "import android.app.Service\nimport android.content.Intent\nimport android.os.IBinder\n\nclass MyService : Service() {\n    override fun onBind(p0: Intent?): IBinder? {\n        TODO(\"Not yet implemented\")\n    }\n\n    override fun onCreate() {\n        super.onCreate()\n    }\n\n    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {\n        return super.onStartCommand(intent, flags, startId)\n    }\n\n    override fun onDestroy() {\n        super.onDestroy()\n    }\n}" },
    { type: "paragraph", text: "Some of the basic methods are" },
    { type: "heading", text: "onCreate()" },
    { type: "paragraph", text: "It likes onCreate() in activity or fragment, it sets up and creates the service." },
    { type: "heading", text: "onStartCommand()" },
    { type: "paragraph", text: "This method will be called when you start the service using startService() command. Using this method, you can send data to the service through the bundle in the intent like you send data to another activity. If you implement this method, you have to stop the service using stopService() or stopSelf() method." },
    { type: "heading", text: "onBind()" },
    { type: "paragraph", text: "onBind() is the minimum method that must be overridden while extending the Service class. If the service type is bound, you should implement this function by returning IBinder. If not(either foreground or background service), you can return null." },
    { type: "heading", text: "onDestroy()" },
    { type: "paragraph", text: "The last called method. You should clean up the resources you used." },
    { type: "heading", text: "How To #Declare The Service" },
    { type: "paragraph", text: "You have to declare your service in manifest with **<service>** tag." },
    { type: "code", code: "<manifest ...\n  <application ... >\n      <service android:name=\".MyService\" />  // Declare your service\n  </application>\n</manifest>" },
    { type: "heading", text: "How To #Start The Service" },
    { type: "paragraph", text: "There are different way to start service based on what type of your service. For **background service** you have to create Intent and pass the service you want. Then, call startService() from your activity or fragment." },
    { type: "code", code: "val serviceIntent = Intent(context, MyService::class.java)\nstartService(serviceIntent)" },
    { type: "paragraph", text: "For **foreground service**, you also have to define the Intent, but to start it, you have to call startForegroundService()" },
    { type: "code", code: "val serviceIntent = Intent(context, MyService::class.java)\nstartForegroundService(serviceIntent)" },
    { type: "paragraph", text: "For **bound service**, you can start and bind to the service by call bindService()" },
    { type: "code", code: "val serviceIntent = Intent(context, MyService::class.java)\nbindService(serviceIntent, connection, Context.BIND_AUTO_CREATE)" },
    { type: "heading", text: "Background Service Example" },
    { type: "paragraph", text: "Let’s create background service which will do the countdown and print the current count in logcat. If the countdown finished, we will show a toast." },
    { type: "paragraph", text: "First, let’s define our service" },
    { type: "code", code: "import android.app.Service\nimport android.content.Intent\nimport android.os.CountDownTimer\nimport android.os.IBinder\nimport android.util.Log\nimport android.widget.Toast\n\nclass CountDownService : Service() {\n    override fun onBind(p0: Intent?): IBinder? {\n        return null\n    }\n\n    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {\n\n        val countDownTimer = object : CountDownTimer(3 * 1000, 100){\n            override fun onTick(tick: Long) {\n                Log.d(\"CountDown\", \"Tick-$tick\")\n            }\n\n            override fun onFinish() {\n                Toast.makeText(this@CountDownService, \"Countdown Finished\", Toast.LENGTH_SHORT).show()\n            }\n\n        }\n\n        countDownTimer.start()\n\n        return START_STICKY\n    }\n\n}" },
    { type: "paragraph", text: "In method onStartCommand, we return an Integer. It describes the system how to continue the service if the system kills it. The constants you can use are" },
    { type: "heading", text: "START_STICKY" },
    { type: "paragraph", text: "Recreate the service but do not deliver last intent" },
    { type: "heading", text: "START_NOT_STICKY" },
    { type: "paragraph", text: "Do not recreate the service unless there are pending intent to deliver" },
    { type: "heading", text: "START_REDELIVER_INTENT" },
    { type: "paragraph", text: "**Recreate** the service and redeliver last intent" },
    { type: "paragraph", text: "Next, we declare the service in manifest" },
    { type: "code", code: "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\"\n    xmlns:tools=\"http://schemas.android.com/tools\">\n\n    <application\n        android:allowBackup=\"true\"\n        android:dataExtractionRules=\"@xml/data_extraction_rules\"\n        android:fullBackupContent=\"@xml/backup_rules\"\n        android:icon=\"@mipmap/ic_launcher\"\n        android:label=\"@string/app_name\"\n        android:roundIcon=\"@mipmap/ic_launcher_round\"\n        android:supportsRtl=\"true\"\n        android:theme=\"@style/Theme.ServiceExample\"\n        tools:targetApi=\"31\">\n        <activity\n            android:name=\".MainActivity\"\n            android:exported=\"true\">\n            <intent-filter>\n                <action android:name=\"android.intent.action.MAIN\" />\n\n                <category android:name=\"android.intent.category.LAUNCHER\" />\n            </intent-filter>\n\n            <meta-data\n                android:name=\"android.app.lib_name\"\n                android:value=\"\" />\n        </activity>\n        <service android:name=\".CountDownService\"/>  // Declare your service\n    </application>" },
    { type: "paragraph", text: "And, last step, we start the service" },
    { type: "code", code: "class MainActivity : AppCompatActivity() {\n    override fun onCreate(savedInstanceState: Bundle?) {\n        super.onCreate(savedInstanceState)\n        setContentView(R.layout.activity_main)\n\n        val serviceIntent = Intent(this, CountDownService::class.java)\n        startService(serviceIntent)\n\n    }\n}" },
    { type: "paragraph", text: "Result" },
    { type: "image", src: "/assets/blog/introduction-to-services-in-android/img-1.png" },
    { type: "paragraph", text: "Countdown Service" },
    { type: "paragraph", text: "That’s it for this post, hope you enjoy reading this. Thanks" },
    { type: "heading", text: "Reference" },
    {
      type: "links",
      items: [
        { label: "Services overview | Android Developers", href: "https://developer.android.com/guide/components/services" },
      ],
    },
  ],
};

export default introductionToServicesInAndroid;
