import type { Post } from "../data";

const quickAndEasyABasicGuideToImplementingDatePickerIn: Post = {
  slug: "quick-and-easy-a-basic-guide-to-implementing-date-picker-in",
  title: "Quick and Easy: A Basic Guide to Implementing Date Picker in Android",
  tag: "Android",
  date: "Mar 2023",
  readTime: "3 min read",
  excerpt: "When it comes to developing Android apps that involve dates, implementing a date picker is often a necessary feature. A date picker allows users to select a specific date from a calendar view, making it a user-friendly way to input dates.",
  cover: "/assets/blog/quick-and-easy-a-basic-guide-to-implementing-date-picker-in/img-1.jpeg",
  link: "https://medium.com/@mrizqi070502/quick-and-easy-a-basic-guide-to-implementing-date-picker-in-android-114b36394953",
  body: [
    { type: "paragraph", text: "When it comes to developing Android apps that involve dates, implementing a date picker is often a necessary feature. A date picker allows users to select a specific date from a calendar view, making it a user-friendly way to input dates. If you’re new to Android development or simply want to refresh your knowledge on implementing a date picker, this guide is for you. In this blog post, we’ll cover the basics of implementing a date picker in Android. So, let’s get started!" },
    { type: "heading", text: "🤔1 — How to Show Date Picker?" },
    { type: "paragraph", text: "Android came up with `DatePickerDialog` that can fulfill your need to get a date from a user. Basically, you just have to create the dialog by passing a context, listener, and initial date then show it." },
    { type: "paragraph", text: "The listener we used is an interface `DatePickerDialog.OnDateListener`. By implementing the listener, you can get the year, month, and day that the user selected. Then use it in whatever you want. In this example, I formatted the date using `SimpleDateFormat.`" },
    { type: "code", code: "// Get the initial date\nval initialDate = Calendar.getInstance()" },
    { type: "code", code: "// Construct the dialog\nval datePickerDialog = DatePickerDialog(\n            this, DatePickerDialog.OnDateSetListener { view, year, month, dayOfMonth ->\n                val date = Calendar.getInstance()\n                date.set(Calendar.YEAR, year)\n                date.set(Calendar.MONTH, month)\n                date.set(Calendar.DAY_OF_MONTH, dayOfMonth)                val simpleDateFormat = SimpleDateFormat(\"EEEE, dd MMMM yyyy\", Locale.getDefault())\n                val formattedDate = simpleDateFormat.format(date.time)                dateTextView.text = formattedDate\n            }, initialDate.get(Calendar.YEAR), initialDate.get(Calendar.MONTH), initialDate.get(Calendar.DAY_OF_MONTH)\n        )// Show the dialog\ndatePickerDialog.show()" },
    { type: "image", src: "/assets/blog/quick-and-easy-a-basic-guide-to-implementing-date-picker-in/img-1.jpeg" },
    { type: "heading", text: "🧐2 — What If I Want To Customize The Style" },
    { type: "paragraph", text: "When you instantiate `DatePickerDialog`, you will notice that there are several possible constructors. Some of them have the option to pass the theme id. So, we can just create a new style that has a parent to a Dialog style. Like this code below, its parent is `@android:style/Theme.DeviceDefault.Light.Dialog` (I tried using a default style like Theme.MaterialComponents.DayNight.DarkActionBar, but it make the dialog not float, fills fullscreen, and the alignment of the date picker is not centered)." },
    { type: "paragraph", text: "The customization is applied to `DatePicker` view and of course, it has xml attributes like you code the view in xml layout. There are a bunch of attributes, you can browse them [**here**](https://developer.android.com/reference/android/widget/DatePicker)." },
    { type: "code", code: "<style name=\"CustomDatePickerDialog\" parent=\"@android:style/Theme.DeviceDefault.Light.Dialog\">\n        <item name=\"android:datePickerStyle\">@style/CustomDatePicker</item>\n    </style>\n    <style name=\"CustomDatePicker\">\n        <item name=\"android:headerBackground\">@color/purple_500</item>\n        <item name=\"android:calendarTextColor\">@color/purple_700</item>\n        <item name=\"android:dayOfWeekBackground\">@android:color/darker_gray</item>\n        <item name=\"android:dayOfWeekTextAppearance\">@style/CustomDayOfWeekTextAppearance</item>\n        <item name=\"android:selectedWeekBackgroundColor\">@color/purple_500</item>\n        <item name=\"android:datePickerMode\">calendar</item>\n    </style>" },
    { type: "code", code: "    <style name=\"CustomDayOfWeekTextAppearance\">\n        <item name=\"android:textColor\">@color/purple_200</item>\n        <item name=\"android:textSize\">14sp</item>\n    </style>" },
    { type: "code", code: "datePickerDialog = DatePickerDialog(\n            this, R.style.CustomDatePickerDialog, DatePickerDialog.OnDateSetListener { view, year, month, dayOfMonth ->\n                val date = Calendar.getInstance()\n                date.set(Calendar.YEAR, year)\n                date.set(Calendar.MONTH, month)\n                date.set(Calendar.DAY_OF_MONTH, dayOfMonth)" },
    { type: "code", code: "                val simpleDateFormat = SimpleDateFormat(\"EEEE, dd MMMM yyyy\", Locale.getDefault())\n                val formattedDate = simpleDateFormat.format(date.time)                dateTextView.text = formattedDate\n            }, initialDate.get(Calendar.YEAR), initialDate.get(Calendar.MONTH), initialDate.get(Calendar.DAY_OF_MONTH)\n        )" },
    { type: "image", src: "/assets/blog/quick-and-easy-a-basic-guide-to-implementing-date-picker-in/img-2.jpeg" },
    { type: "heading", text: "😲3 — Is There Any Other Date Picker Library?" },
    { type: "paragraph", text: "Yes, There is. One I know that commonly used is [Material Design](https://m2.material.io/). To use it is quite easy." },
    { type: "paragraph", text: "Declare the Material Dependency in `app/build.gradle` (Commonly, it’s already added by Android Studio when you create a new project). Make sure the `repositories` section includes Google's Maven Repository `google()`." },
    { type: "code", code: "allprojects {\n    repositories {\n      google()\n      mavenCentral()\n    }\n  }" },
    { type: "code", code: "dependencies {\n    // ...\n    implementation 'com.google.android.material:material:1.8.0'\n    // ...\n  }" },
    { type: "paragraph", text: "Next, construct the `MaterialDatePicker` using the builder. You can set the title, the initially selected date, positive button text, negative button text, etc." },
    { type: "paragraph", text: "If you want to get the selected date after the user clicks the positive button, add a listener to the `MaterialDatePicker` . You will get the date in the type of `Long` . Use any date API you want (I use `Date`) to format the data you got." },
    { type: "code", code: "val materialDatePicker = MaterialDatePicker.Builder.datePicker()\n            .setTitleText(\"Select date\")\n            .setSelection(MaterialDatePicker.todayInUtcMilliseconds())\n            .setPositiveButtonText(\"Submit\")\n            .build()" },
    { type: "code", code: "materialDatePicker.addOnPositiveButtonClickListener {timeInMillis ->\n            Toast.makeText(this, \"Submitted\", Toast.LENGTH_SHORT).show()\n            val date = Date(timeInMillis)\n            val simpleDateFormat = SimpleDateFormat(\"EEEE, dd MMMM yyyy\", Locale.getDefault())\n            val formattedDate = simpleDateFormat.format(date)\n            dateTextView.text = formattedDate\n        }materialDatePicker.addOnNegativeButtonClickListener {\n            Toast.makeText(this, \"Cancelled\", Toast.LENGTH_SHORT).show()\n        }materialDatePicker.show(supportFragmentManager, \"Material 2 Date Picker\")" },
    { type: "image", src: "/assets/blog/quick-and-easy-a-basic-guide-to-implementing-date-picker-in/img-3.jpeg" },
    { type: "heading", text: "😃4 — Can I Set the Minimum and Maximum Date That Can Be Selected?" },
    { type: "paragraph", text: "Of course you can, In Android `DatePickerDialog`, set the min and max date by using the `DatePicker` object." },
    { type: "code", code: "val minDate = initialDate.plusDays(-3)\nval maxDate = initialDate.plusDays(3)\ndatePickerDialog.datePicker.minDate = minDate.atStartOfDay(ZoneId.systemDefault()).toInstant().toEpochMilli()\ndatePickerDialog.datePicker.maxDate = maxDate.atStartOfDay(ZoneId.systemDefault()).toInstant().toEpochMilli()" },
    { type: "image", src: "/assets/blog/quick-and-easy-a-basic-guide-to-implementing-date-picker-in/img-4.jpeg" },
    { type: "paragraph", text: "In `MaterialDatePicker`, you have to create the `CalendarConstraints` and you can just set the min and max date in level of month, not date like previous example." },
    { type: "code", code: "val calendar = Calendar.getInstance()\n        calendar[Calendar.MONTH] = Calendar.JANUARY\n        val january = calendar.timeInMillis\n        calendar[Calendar.MONTH] = Calendar.APRIL\n        val april = calendar.timeInMillis\n        calendar[Calendar.MONTH] = Calendar.JUNE\n        val june = calendar.timeInMillis" },
    { type: "code", code: "val constrainsBuilder = CalendarConstraints.Builder()\n            .setStart(january)\n            .setEnd(june)\n            .setOpenAt(april)val materialDatePicker = MaterialDatePicker.Builder.datePicker()\n            .setTitleText(\"Select date\")\n            .setSelection(MaterialDatePicker.todayInUtcMilliseconds())\n            .setPositiveButtonText(\"Submit\")\n            .setCalendarConstraints(constrainsBuilder.build())\n            .build()" },
    { type: "image", src: "/assets/blog/quick-and-easy-a-basic-guide-to-implementing-date-picker-in/img-5.gif" },
    { type: "heading", text: "😀5 — Is It Possible to Pick Range of Date? How?" },
    { type: "paragraph", text: "If you want to pick a range of dates, you can use `MaterialDatePicker` . It has `dateRangePicker()` component. The instantiation process is quite similar to date picker. The difference is, when you set the initially selected date, you have to pass a Pair of dates (start date and end date). And, in the positive listener, you will have a pair of dates (start and end date)." },
    { type: "code", code: "val materialDatePicker = MaterialDatePicker.Builder.dateRangePicker()\n            .setTitleText(\"Select date\")\n            .setSelection(\n                androidx.core.util.Pair(\n                    MaterialDatePicker.thisMonthInUtcMilliseconds(),\n                    MaterialDatePicker.todayInUtcMilliseconds()\n                )\n            )\n            .setPositiveButtonText(\"Submit\")\n            .build()" },
    { type: "code", code: "materialDatePicker.addOnPositiveButtonClickListener {pair ->\n            Toast.makeText(this, \"Submitted\", Toast.LENGTH_SHORT).show()\n            val simpleDateFormat = SimpleDateFormat(\"EEEE, dd MMMM yyyy\", Locale.getDefault())            val startDate = Date(pair.first)\n            val formattedStartDate = simpleDateFormat.format(startDate)            val endDate = Date(pair.second)\n            val formattedEndDate = simpleDateFormat.format(endDate)\n            dateTextView.text = \"$formattedStartDate until $formattedEndDate\"\n        }" },
    { type: "image", src: "/assets/blog/quick-and-easy-a-basic-guide-to-implementing-date-picker-in/img-6.jpeg" },
    { type: "paragraph", text: "Yay 🎉, we just learn how to show a date picker and get the date from the user. So far, we already know the `DatePickerDialog` from Android, `MaterialDatePicker` from Material Design, how to customize it, and many more. Hope this blog helps you with your project. [**Follow me**](https://medium.com/@mrizqi070502/about) to get more about Android Development posts. Let’s connect on [**LinkedIn**](https://www.linkedin.com/in/m-rizqi/) and [**Instagram**](https://www.instagram.com/_riz.qi/)" },
    { type: "heading", text: "Reference" },
    {
      type: "links",
      items: [
        { label: "DatePickerDialog | Android Developers", href: "https://developer.android.com/reference/android/app/DatePickerDialog#public-methods_1" },
        { label: "DatePicker | Android Developers", href: "https://developer.android.com/reference/android/widget/DatePicker" },
        { label: "Date pickers — Material Design", href: "https://m2.material.io/components/date-pickers" },
      ],
    },
  ],
};

export default quickAndEasyABasicGuideToImplementingDatePickerIn;
